#!/usr/bin/sh

TOP=`pwd`
PREFIX=~/.local
PYTHON=python
PYVER=`$PYTHON -c "import sys; print('%i.%i' % sys.version_info[0:2])"`

#====================================================================
# cleanup
#====================================================================
if [ -e $PREFIX/bin/waf ]
then
	rm -v $PREFIX/bin/waf
fi

if [ -d $PREFIX/bin/.waf-$VERSION* ]
then
	rm -vrf $PREFIX/bin/.waf-$VERSION*
fi

if [ -d $PREFIX/share/waf ]
then
	rm -vrf $PREFIX/share/waf
fi

if [ -d $PREFIX/lib/python$PYVER/site-packages/waflib ]
then
	rm -vrf $PREFIX/lib/python$PYVER/site-packages/waflib
fi

#====================================================================
# uninstall waftools
#====================================================================
TMPFILE=.files_waftools
if [ ! -e $TMPFILE ]
then
	$PYTHON setup.py install --prefix=$PREFIX --record $TMPFILE
fi

DIRNAME=`head -1 $TMPFILE | xargs dirname`
if [ -d $DIRNAME ]
then
	rm -vrf $DIRNAME
fi





